### ISSUE TITLE
Support hub api-server host alias

### ISSUE THREAD

**Issue by promacanthus** [open-cluster-management-io/api#165]
In some cases, the server in the Hub cluster kubeconfig file is a domain name. For example, as shown in the example below.

```yaml
apiVersion: v1
kind: Config
clusters:
- cluster:
    server: https://xxx.yyy.com
```

The contents of this kubeconfig file will be stored in the namespace(open-cluster-manager-agent) in the secret(bootstrap-hub-kubeconfig) as the startup configuration when the managed cluster is registered.

The registration-agent will use this bootstrap-hub-kubeconfig to create CRD(managedCluster) and CSR, but the following error message will be encountered in the logs.

```shell
E0623 03:02:35.268397       1 reflector.go:138] k8s.io/client-go@v0.23.0/tools/cache/reflector.go:167: Failed to watch *v1.CertificateSigningRequest: failed to list *v1.CertificateSigningRequest: Get "https://xxx.yyy.com/apis/certificates.k8s.io/v1/certificatesigningrequests?limit=500&resourceVersion=0": dial tcp: lookup xxx.yyy.com on 10.xx.yy.zz:53: no such host
```

This is because the domain name of the Hub Cluster API Server is not available in the managed cluster's DNS servers. The solution to this problem is simply to write the host alias to the registration-agent pod. This is shown below.

```yaml
spec:
hostAliases:
- ip: "xx.xx.xx.xx"
  hostnames:
  -  "xxx.yyy.com"
```
----------

For the above problem and solution, the API needs to be modified, and the specific design and implementation are as follows.

Add a new field named HubApiServerHostAlias to the KlusterletSpec.

```golang
type KlusterletSpec struct {

	// ...

	// HubApiServerHostAlias contains the host alias for hub api server
	// +optional
	HubApiServerHostAlias *v1.HostAlias `json:"hub_api_server_host_alias,omitempty"`
}
```

**[Registration-operator](https://github.com/open-cluster-management-io/registration-operator)** Repo

Add a new rendering logic to  [manifests/klusterlet/management/klusterlet-registration-deployment.yaml](https://github.com/open-cluster-management-io/registration-operator/blob/main/manifests/klusterlet/management/klusterlet-registration-deployment.yaml) template.

```yaml
spec:
{{if .HostAlias }}
hostAliases:
- ip: {{ .HostAlias.Ip }}
  hostnames:
  {{range .HostAlias.Hostnames }}
  - {{ . }}
  {{end}}
{{end}}
```

Add helper function in [pkg/helpers/helpers.go](https://github.com/open-cluster-management-io/registration-operator/blob/main/pkg/helpers/helpers.go) to get the value to be rendered from the Klusterlet configuration file.

```golang
func HubApiServerHostAlias(klusterlet *operatorapiv1.Klusterlet) *corev1.HostAlias {
	if len(klusterlet.Spec.HubApiServerHostAlias) == 0 {
		return nil
	}

	return &corev1.HostAlias{
		IP: klusterlet.Spec.HubApiServerHostAlias.IP,
		Hostnames: klusterlet.Spec.HubApiServerHostAlias.Hostnames,
	}
}
```
